config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    resources :comments
    member do
      get 'like', to: 'pictures#like'
      get 'unlike', to: 'pictures#unlike'
    end
  end
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pictures#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
      can :read, :all
    #
      return unless user.present?
      can :manage, Picture, user_id: user.id
      can :manage, Comment, user_id: user.id
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, :title, presence: true

  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy

  is_impressionable
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def set_user_picture
    @picture = Picture.find(params[:picture_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    set_user_picture
    @comment = @picture.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save!

    respond_to do |format|
      format.html { redirect_to picture_path(@picture), notice: "Comment was successfully created." }
      format.json { head :no_content }
    end
  end

  def destroy
    set_user_picture
    @comment = @picture.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to picture_path(@picture), alert: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end


  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:name, :reply)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy like unlike]
  before_action :authenticate_user!, except: %i[ show index like unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]


  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all.order('created_at DESC')
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = current_user.pictures.build
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @picture.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @picture.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:title, :description, :user_id, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :name)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/_comment.html.erb
<div style="background-color: rgb(193,206,193)">
<div class="d-flex card-body mx-5 my-3 rounded" style="background-color: rgb(218,228,217)">
  <div class="flex-shrink-0">
        <%= gravatar_image_tag(comment.user.email, class: "avatar-comment", alt: @picture.user.name) %>
    </div>
    <div class="flex-grow-1 ms-3">
        <h5><small><%= comment.user.name %><i class="text-muted"> posted <%= time_ago_in_words(comment.created_at)%> ago</i></small></h5>
        <p><%= comment.reply %></p>
    </div>
      <% if can? :update, comment %>
        <%= button_to "Delete post", [comment.picture, comment], method: :delete, class: "btn btn-light shadow-sm" %>
      <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@picture, @picture.comments.build]) do |f| %>

  <div class="mb-2">
      <%= f.input :reply, label: false, input_html: { class: 'textarea', placeholder: "Add a comment...", rows: 4, style: "background-color: #FEFFFA"}, label_html: { class: 'form-label' } %>
  </div>

  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark  mb-4" style="background-color: #475C4D;">
  <div class="container-fluid">
    <a class="navbar-brand disabled">Artistico</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <%= link_to "Pictures", root_path, class:"nav-link nav-item ms-3", id: "nav-link-color" %>
       <% if user_signed_in? %>
         <div class="navbar-nav me-auto mb-2 mb-lg-0  ms-4">
           <%= link_to "Upload Picture", new_picture_path, class:"btn btn-success", id: "nav-link-color" %>
         </div>
         <div class="navbar-nav">
           <%= link_to "My Account", edit_user_registration_path, method: :delete, class:"nav-link", id: "nav-link-color" %>
           <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link", id: "nav-link-color" %>
         </div>
       <% else %>
         <div class="navbar-nav me-auto mb-2 mb-lg-0"></div>
         <div class="navbar-nav">
           <%= link_to "Log In", new_user_session_path, class:"nav-link", id: "nav-link-color" %>
           <%= link_to "Sign Up", new_user_registration_path, class:"nav-link", id: "nav-link-color" %>
         </div>
       <% end %>
     </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artistico</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- kit code for bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- kit code for FontAwesome -->
    <script src="https://kit.fontawesome.com/0261824874.js" crossorigin="anonymous"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if flash[:notice] %>
          <p class="notice alert alert-primary"><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
          <p class="alert alert alert-warning"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= simple_form_for(@picture) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :image, label: "Choose Picture to Upload", input_html: { type: "file",  class: "form-control" } %>
        <br>
        <%= f.input :title %>
        <br>
        <%= f.input :description, :input_html => { :rows => 10 }%>
      </div>

      <div class="form-actions my-4">
        <%= f.button :submit, "Submit Now", class:"btn btn-success btn-lg"   %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">

  <% if picture.image.attached? %>
    <%= image_tag picture.image, style: "width: 200px; display: block" %>
    <% end %>
  <p>
    <%= picture.title %>
  </p>

  <p>
    <small>By <%= picture.user.name %></small>
  </p>

<!--   <p>
    <strong>User:</strong>
    <%= picture.user_id %>
  </p> -->

</div>

app/views/pictures/edit.html.erb
<h1 class="text-center mb-4">Edit Picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Show this picture", @picture %> |
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/index.html.erb
<div id="pictures" class="d-inline-flex justify-content-center">
  <% @pictures.each do |picture| %>

  <div><%= link_to picture, class: "picture" do %>
    <%= image_tag polymorphic_url(picture.image.variant(resize_to_fit: [250, 250]).processed, only_path: true), class: "img-thumbnail" %>
    <% end %>

    <div class="d-flex justify-content-around mb-4" id="index-all-pictures">
      <div class="view-thumbnail">
        <%= link_to picture do %>
        <span class="icon"><i class="fa fa-eye"></i></span>
        <span class="thumbnail-count"><%= picture.impressionist_count %></span>
        <% end %>
      </div>
      <div class="comment-thumbnail">
        <%= link_to picture do %>
        <span class="icon"><i class="fa fa-comment"></i></span>
        <span class="thumbnail-count"><%= picture.comments.count %></span>
        <% end %>
      </div>
      <div class="like-thumbnail">
       <% if user_signed_in? %>

          <% if current_user.liked? picture %>
            <%= link_to unlike_picture_path(picture), method: :put do %>
              <span class="icon"><i class="fa fa-heart" style="color: #E71021;"></i></span>
              <span class="thumbnail-count"><%= picture.get_likes.size %></span>
            <% end %>
          <% else %>
            <%= link_to like_picture_path(picture), method: :put do %>
              <span class="icon"><i class="fa fa-heart"></i></span>
              <span class="thumbnail-count"><%= picture.get_likes.size %></span>
            <% end %>
          <% end %>
        <% else %>
            <%= link_to like_picture_path(picture), method: :put do %>
              <span class="icon"><i class="fa fa-heart"></i></span>
              <span class="thumbnail-count"><%= picture.get_likes.size %></span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<h1 class="text-center mb-4">Upload Picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Back to pictures", pictures_path%>
</div>

app/views/pictures/show.html.erb
<section class="content-item rounded">
  <div class="container">
    <div class="row">
      <div class="col col-sm-8">
        <div class="d-flex flex-column">
          <%= image_tag polymorphic_url(@picture.image.variant(resize_to_limit: [818, nil]).processed, only_path: true), class: "img-fluid" %>
          <% if can? :update, @picture %>
          <div class="box d-flex gap-2">
            <small><%= link_to "Edit this picture", edit_picture_path(@picture), class: "btn btn-light shadow-sm" %></small>

            <small><%= button_to "Destroy this picture", @picture, method: :delete, class: "btn btn-light shadow-sm" %></small>
          </div>
          <% end %></div>
        </div>
        <div class="col col-sm-4">
          <div class="content-title mb-2">
            <h1> <%= @picture.title %></h1>
            <div class="d-flex">
              <div class="me-2"><%= gravatar_image_tag(@picture.user.email, class: "avatar-small", alt: @picture.user.name) %>
              </div>
              <div class="mt-2">
                <small><%= @picture.user.name %></small>
                <br>
                <small>posted <%= time_ago_in_words(@picture.created_at)%> ago</small>
              </div>

            </div>
          </div>
          <div class="box">
            <%= @picture.description%>
          </div>
          <div class="box">
            <ul class="list-unstyled">
              <li>
               <% if user_signed_in? %>

               <% if current_user.liked? @picture %>
               <%= link_to unlike_picture_path(@picture), class: "show-icon-text", method: :put do %>
               <i class="fa fa-heart" style="color: #E71021;"></i><%= pluralize(@picture.get_likes.size, "Like") %>
               <% end %>
               <% else %>
               <%= link_to like_picture_path(@picture), class: "show-icon-text", method: :put do %>
               <i class="fa fa-heart"></i><%= pluralize(@picture.get_likes.size, "Like") %>
               <% end %>
               <% end %>
               <% else %>
               <%= link_to like_picture_path(@picture), class: "show-icon-text", method: :put do %>
               <i class="fa fa-heart"></i><%= pluralize(@picture.get_likes.size, "Like") %>
               <% end %>
               <% end %>
             </li>
             <li>
              <i class="fa fa-eye"></i><%= pluralize(@picture.impressionist_count, "View") %>
            </li>
            <li>
              <i class="fa fa-comment"></i><%= pluralize(@picture.comments.count, "Comment") %>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</section>

<section>

</section>

<section>
  <div class="card my-4">
    <div class="card-header" id="comment-card-header">
      <h2>Comments</h2>
    </div>
    <%= render @picture.comments %>
    <div class="card-body" style="background-color: rgb(193,206,193);" >
      <% if user_signed_in? %>
      <%= render 'comments/form' %>
      <% else %>
      <div>To leave a comment, please <%= link_to 'Sign in.', new_user_session_path %></div>
      <% end %>
      <hr />
    </div>
  </div>
</section>